travis - try a more sophisticated yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,63 +1,90 @@
+#  https://github.com/andstatus/andstatus/blob/master/.travis.yml
 language: android
-
 addons:
   apt:
     packages:
-      - oracle-java8-installer
       - lynx
-
+jdk:
+- oraclejdk8
+env:
+  global:
+  - ANDROID_API=27
+  - EMULATOR_API=24
+  - ANDROID_BUILD_TOOLS=27.0.2
 android:
   components:
-    - tools
-    - platform-tools
-    - tools # appears twice as per Travis docs
-    - build-tools-23.0.1
-    - build-tools-27.0.2
-    - android-4
-    - android-10
-    - android-19
-    - android-23
-    - android-25
-    - extra-android-m2repository
-    - sys-img-armeabi-v7a-android-25
-
+  - tools
+  - android-$EMULATOR_API
+  - platform-tools
+  - tools
+  - build-tools-$ANDROID_BUILD_TOOLS
+  - android-$ANDROID_API
+  - extra-android-support
+  - extra-android-m2repository
+  - extra-google-m2repository
+  - sys-img-armeabi-v7a-android-$EMULATOR_API
   licenses:
-    - 'android-sdk-license-.+'
-
-env:
-  matrix:
-    - ANDROID_TARGET=android-4 ANDROID_ABI=armeabi
-    - ANDROID_TARGET=android-10 ANDROID_ABI=armeabi
-    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
-    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
-
-before_install:
-  - yes | sdkmanager "platforms;android-27" # https://github.com/travis-ci/travis-ci/issues/8874
-before_cache:
-  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
-cache:
-  directories:
-    - $HOME/.gradle/caches/
-    - $HOME/.gradle/wrapper/
-    - $HOME/.android/build-cache/
-
+  - ".+"
 before_script:
-  # Create and start emulator
-  - android list targets
-  - jdk_switcher use oraclejdk8
-  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
-  - emulator -avd test -no-skin -no-audio -no-window &
-  - adb wait-for-device
-  - while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
-  - adb shell input keyevent 82 &
+- echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_API
+- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_API
+- android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
+- echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
+- emulator -avd test -no-skin -no-window &
+- android-wait-for-emulator
+- adb shell input keyevent 82 &
+- adb wait-for-device get-serialno
+- cd ${TRAVIS_BUILD_DIR}
+- chmod +x gradlew
+- ./gradlew --version
+- ./gradlew clean
+
+  #./gradlew build assembleAndroidTest -PtestCoverageEnabled='true'
+  
+script:
+- |
+
+  ./gradlew build assembleAndroidTest
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error on assembling, exit code: "$retval
+    exit $retval
+  fi
+# See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
+# Instead of this (which doesn't give any output during tests execution):
+# - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
+# run:
+
+# ./gradlew :app:installDebug :app:installDebugAndroidTest -PtestCoverageEnabled='true'
+
+- |
+
+  ./gradlew :app:installDebug :app:installDebugAndroidTest
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error on install, exit code: "$retval
+    exit $retval
+  fi
 
 script:
     - cd TextStyling-Java;   ./gradlew -Pci --console=plain :app:testDebug
     - ./gradlew build connectedCheck
     - cd ../TextStyling-Kotlin; ./gradlew -Pci --console=plain :app:testDebug
     - ./gradlew build connectedCheck
-
 after_failure:
   - if [ -f /home/travis/build/jimandreas/android-text/TextStyling-Kotlin/app/build/reports/tests/testDebugUnitTest/index.html ]; then lynx -dump /home/travis/build/jimandreas/android-text/TextStyling-Kotlin/app/build/reports/tests/testDebugUnitTest/index.html; fi
   - if [ -f /home/travis/build/jimandreas/android-text/TextStyling-Java/app/build/reports/androidTests/connected/index.html ];    then lynx -dump /home/travis/build/jimandreas/android-text/TextStyling-Java/app/build/reports/androidTests/connected/index.html; fi
   - if [ -f /home/travis/build/jimandreas/android-text/TextStyling-Kotlin/app/build/reports/androidTests/connected/index.html ]; then lynx -dump  /home/travis/build/jimandreas/android-text/TextStyling-Kotlin/app/build/reports/androidTests/connected/index.html; fi
+
+notifications:
+  email: false
+cache:
+  directories:
+  - $HOME/.m2
+  - $HOME/.gradle/caches/
+  - $HOME/.gradle/wrapper/
+  - $HOME/.android/build-cache
+before_install:
+- yes | sdkmanager "platforms;android-27"
+#after_success:
+#  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true
